<template>
  <div id="shangping">
    <!-- 渲染做左边数据 -->
    <div class="left">
      <ul class="">
        <li
          v-for="(item, index) in left"
          :key="index"
          class="font24 flex flex-ac plr25"
          :style="index == i ? 'background:white' : ''"
          @click="add(index)"
        >
        <p class=" cutFont"> {{ item.name }}</p>
         
        </li>
      </ul>
    </div>
    <!-- 渲染右边方案一写法 -->
       <div class="right" @scroll="gun" ref="gun">
      <ul class="box" ref="box" >
        <li v-for="(item1, index1) in left" :key="index1" :ref="index1 + '1'">
          <p class="font24 gray">{{ item1.name }}</p>

          <ul >
            <li v-for="(item, index) in item1.foods" :key="index" class="flex">
              <div class="img" @click="xiang(item)">
                <img :src="item.image" alt="" />
              </div>
              <div class="ml20 font20 cont-r">
                <h3 class="font28">{{ item.name }}</h3>
                <p class="gray">{{ item.description }}</p>
                <p class="gray">
                  月销量{{ item.sellCount }} 好评{{ item.rating }}%
                </p>
                <p class="red font28 fb">
                  ￥{{ item.price }}
                  <small class="gray del" v-if="item.oldPrice != ''"
                    >￥{{ item.oldPrice }}</small
                  >
                </p>
              </div>
              <div class="tubiao flex flex-ac">
                <div   v-show="item.num>0">
                  <svg
                    @click="jianjian(item)"
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                  
                    viewBox="0 0 768 768"
                  >
                    <g id="icomoon-ignore">
                      <line
                        stroke-width="1"
                        x1="16"
                        y1="0"
                        x2="16"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="32"
                        y1="0"
                        x2="32"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="48"
                        y1="0"
                        x2="48"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="64"
                        y1="0"
                        x2="64"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="80"
                        y1="0"
                        x2="80"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="96"
                        y1="0"
                        x2="96"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="112"
                        y1="0"
                        x2="112"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="128"
                        y1="0"
                        x2="128"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="144"
                        y1="0"
                        x2="144"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="160"
                        y1="0"
                        x2="160"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="176"
                        y1="0"
                        x2="176"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="192"
                        y1="0"
                        x2="192"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="208"
                        y1="0"
                        x2="208"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="224"
                        y1="0"
                        x2="224"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="240"
                        y1="0"
                        x2="240"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="256"
                        y1="0"
                        x2="256"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="272"
                        y1="0"
                        x2="272"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="288"
                        y1="0"
                        x2="288"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="304"
                        y1="0"
                        x2="304"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="320"
                        y1="0"
                        x2="320"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="336"
                        y1="0"
                        x2="336"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="352"
                        y1="0"
                        x2="352"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="368"
                        y1="0"
                        x2="368"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="384"
                        y1="0"
                        x2="384"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="400"
                        y1="0"
                        x2="400"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="416"
                        y1="0"
                        x2="416"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="432"
                        y1="0"
                        x2="432"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="448"
                        y1="0"
                        x2="448"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="464"
                        y1="0"
                        x2="464"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="480"
                        y1="0"
                        x2="480"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="496"
                        y1="0"
                        x2="496"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="512"
                        y1="0"
                        x2="512"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="528"
                        y1="0"
                        x2="528"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="544"
                        y1="0"
                        x2="544"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="560"
                        y1="0"
                        x2="560"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="576"
                        y1="0"
                        x2="576"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="592"
                        y1="0"
                        x2="592"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="608"
                        y1="0"
                        x2="608"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="624"
                        y1="0"
                        x2="624"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="640"
                        y1="0"
                        x2="640"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="656"
                        y1="0"
                        x2="656"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="672"
                        y1="0"
                        x2="672"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="688"
                        y1="0"
                        x2="688"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="704"
                        y1="0"
                        x2="704"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="720"
                        y1="0"
                        x2="720"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="736"
                        y1="0"
                        x2="736"
                        y2="768"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="752"
                        y1="0"
                        x2="752"
                        y2="768"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="16"
                        x2="768"
                        y2="16"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="32"
                        x2="768"
                        y2="32"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="48"
                        x2="768"
                        y2="48"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="64"
                        x2="768"
                        y2="64"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="80"
                        x2="768"
                        y2="80"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="96"
                        x2="768"
                        y2="96"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="112"
                        x2="768"
                        y2="112"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="128"
                        x2="768"
                        y2="128"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="144"
                        x2="768"
                        y2="144"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="160"
                        x2="768"
                        y2="160"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="176"
                        x2="768"
                        y2="176"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="192"
                        x2="768"
                        y2="192"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="208"
                        x2="768"
                        y2="208"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="224"
                        x2="768"
                        y2="224"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="240"
                        x2="768"
                        y2="240"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="256"
                        x2="768"
                        y2="256"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="272"
                        x2="768"
                        y2="272"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="288"
                        x2="768"
                        y2="288"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="304"
                        x2="768"
                        y2="304"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="320"
                        x2="768"
                        y2="320"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="336"
                        x2="768"
                        y2="336"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="352"
                        x2="768"
                        y2="352"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="368"
                        x2="768"
                        y2="368"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="384"
                        x2="768"
                        y2="384"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="400"
                        x2="768"
                        y2="400"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="416"
                        x2="768"
                        y2="416"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="432"
                        x2="768"
                        y2="432"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="448"
                        x2="768"
                        y2="448"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="464"
                        x2="768"
                        y2="464"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="480"
                        x2="768"
                        y2="480"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="496"
                        x2="768"
                        y2="496"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="512"
                        x2="768"
                        y2="512"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="528"
                        x2="768"
                        y2="528"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="544"
                        x2="768"
                        y2="544"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="560"
                        x2="768"
                        y2="560"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="576"
                        x2="768"
                        y2="576"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="592"
                        x2="768"
                        y2="592"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="608"
                        x2="768"
                        y2="608"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="624"
                        x2="768"
                        y2="624"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="640"
                        x2="768"
                        y2="640"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="656"
                        x2="768"
                        y2="656"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="672"
                        x2="768"
                        y2="672"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="688"
                        x2="768"
                        y2="688"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="704"
                        x2="768"
                        y2="704"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="720"
                        x2="768"
                        y2="720"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="736"
                        x2="768"
                        y2="736"
                        stroke="#449FDB"
                        opacity="1"
                      ></line>
                      <line
                        stroke-width="1"
                        x1="0"
                        y1="752"
                        x2="768"
                        y2="752"
                        stroke="#449FDB"
                        opacity="0.3"
                      ></line>
                    </g>
                    <path
                      d="M384 640.5q105 0 180.75-75.75t75.75-180.75-75.75-180.75-180.75-75.75-180.75 75.75-75.75 180.75 75.75 180.75 180.75 75.75zM384 64.5q132 0 225.75 93.75t93.75 225.75-93.75 225.75-225.75 93.75-225.75-93.75-93.75-225.75 93.75-225.75 225.75-93.75zM223.5 352.5h321v63h-321v-63z"
                    ></path>
                  </svg>

                  <i class="font30 mlr20">{{ item.num }}</i>
                </div>
                <svg
                  @click="shul(item,item)"
                 
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
               
                  viewBox="0 0 768 768"
                >
                  <g id="icomoon-ignore">
                    <line
                      stroke-width="1"
                      x1="16"
                      y1="0"
                      x2="16"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="32"
                      y1="0"
                      x2="32"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="48"
                      y1="0"
                      x2="48"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="64"
                      y1="0"
                      x2="64"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="80"
                      y1="0"
                      x2="80"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="96"
                      y1="0"
                      x2="96"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="112"
                      y1="0"
                      x2="112"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="128"
                      y1="0"
                      x2="128"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="144"
                      y1="0"
                      x2="144"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="160"
                      y1="0"
                      x2="160"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="176"
                      y1="0"
                      x2="176"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="192"
                      y1="0"
                      x2="192"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="208"
                      y1="0"
                      x2="208"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="224"
                      y1="0"
                      x2="224"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="240"
                      y1="0"
                      x2="240"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="256"
                      y1="0"
                      x2="256"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="272"
                      y1="0"
                      x2="272"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="288"
                      y1="0"
                      x2="288"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="304"
                      y1="0"
                      x2="304"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="320"
                      y1="0"
                      x2="320"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="336"
                      y1="0"
                      x2="336"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="352"
                      y1="0"
                      x2="352"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="368"
                      y1="0"
                      x2="368"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="384"
                      y1="0"
                      x2="384"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="400"
                      y1="0"
                      x2="400"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="416"
                      y1="0"
                      x2="416"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="432"
                      y1="0"
                      x2="432"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="448"
                      y1="0"
                      x2="448"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="464"
                      y1="0"
                      x2="464"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="480"
                      y1="0"
                      x2="480"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="496"
                      y1="0"
                      x2="496"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="512"
                      y1="0"
                      x2="512"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="528"
                      y1="0"
                      x2="528"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="544"
                      y1="0"
                      x2="544"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="560"
                      y1="0"
                      x2="560"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="576"
                      y1="0"
                      x2="576"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="592"
                      y1="0"
                      x2="592"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="608"
                      y1="0"
                      x2="608"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="624"
                      y1="0"
                      x2="624"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="640"
                      y1="0"
                      x2="640"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="656"
                      y1="0"
                      x2="656"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="672"
                      y1="0"
                      x2="672"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="688"
                      y1="0"
                      x2="688"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="704"
                      y1="0"
                      x2="704"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="720"
                      y1="0"
                      x2="720"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="736"
                      y1="0"
                      x2="736"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="752"
                      y1="0"
                      x2="752"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="16"
                      x2="768"
                      y2="16"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="32"
                      x2="768"
                      y2="32"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="48"
                      x2="768"
                      y2="48"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="64"
                      x2="768"
                      y2="64"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="80"
                      x2="768"
                      y2="80"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="96"
                      x2="768"
                      y2="96"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="112"
                      x2="768"
                      y2="112"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="128"
                      x2="768"
                      y2="128"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="144"
                      x2="768"
                      y2="144"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="160"
                      x2="768"
                      y2="160"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="176"
                      x2="768"
                      y2="176"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="192"
                      x2="768"
                      y2="192"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="208"
                      x2="768"
                      y2="208"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="224"
                      x2="768"
                      y2="224"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="240"
                      x2="768"
                      y2="240"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="256"
                      x2="768"
                      y2="256"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="272"
                      x2="768"
                      y2="272"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="288"
                      x2="768"
                      y2="288"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="304"
                      x2="768"
                      y2="304"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="320"
                      x2="768"
                      y2="320"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="336"
                      x2="768"
                      y2="336"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="352"
                      x2="768"
                      y2="352"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="368"
                      x2="768"
                      y2="368"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="384"
                      x2="768"
                      y2="384"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="400"
                      x2="768"
                      y2="400"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="416"
                      x2="768"
                      y2="416"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="432"
                      x2="768"
                      y2="432"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="448"
                      x2="768"
                      y2="448"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="464"
                      x2="768"
                      y2="464"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="480"
                      x2="768"
                      y2="480"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="496"
                      x2="768"
                      y2="496"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="512"
                      x2="768"
                      y2="512"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="528"
                      x2="768"
                      y2="528"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="544"
                      x2="768"
                      y2="544"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="560"
                      x2="768"
                      y2="560"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="576"
                      x2="768"
                      y2="576"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="592"
                      x2="768"
                      y2="592"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="608"
                      x2="768"
                      y2="608"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="624"
                      x2="768"
                      y2="624"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="640"
                      x2="768"
                      y2="640"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="656"
                      x2="768"
                      y2="656"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="672"
                      x2="768"
                      y2="672"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="688"
                      x2="768"
                      y2="688"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="704"
                      x2="768"
                      y2="704"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="720"
                      x2="768"
                      y2="720"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="736"
                      x2="768"
                      y2="736"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="752"
                      x2="768"
                      y2="752"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                  </g>
                  <path
                    d="M544.5 415.5v-63h-129v-129h-63v129h-129v63h129v129h63v-129h129zM384 64.5q132 0 225.75 93.75t93.75 225.75-93.75 225.75-225.75 93.75-225.75-93.75-93.75-225.75 93.75-225.75 225.75-93.75z"
                  ></path>
                </svg>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- 只在商品内显示的购物车组件 -->
    <gouwuche :jiage="jiage"></gouwuche>
  </div>
</template>

<script>
//引入购物车组件
import gouwuche from '../components/gouwuche2.vue'
export default {
  data() {
    return {
      shangping: {},
      left: [],
      i: 0,
      jiage: [],
      xian: [],
      changdu: [],
    };
  },
  //注册购物车组件
  components: {
    gouwuche
  },

  mounted() {
    // 通过axios进行数据的调用
    this.axios.get("data/data.json").then((d) => {
       console.log(d)
      var { data } = d;
      this.shangping = data;
      this.left = this.shangping.goods;
    });
    // 方案二
    setTimeout(()=>{
      for(var i=0;i<this.left.length;i++){
      var k=this.$refs[i + "1"][0].offsetTop-this.$refs.gun.offsetTop;  
          this.changdu.push(k)
      }
    },100)
  },

  methods: {
    add(i) {
      // 方案一写法
      this.i = i;
      this.$refs.gun.scrollTop=this.changdu[i]
    },
    // 累加，
    // 参数代表当前点击的数据,并且使用push添加到价格的数组里进行对购物车的父子组件传值
    // 现阶段发现如果单独使用push会导致第二次加的时候依旧往数组里添加对象，而造成出现2个相同的数据
    // 好比如我第一次点击添加是正常的显示总价为当前的单价，但是我再次点击相同的商品添加时购物车就会出现2个一样的数据就相当于算了4份的价格
    // 问题：push在num++时会一直累加，而需要的是只显示单品的数量累加
    // 解决：使用this.jiage=[...new Set(this.jiage)]就能解决问题
    shul(i,item) {
      i.num++;
      // console.log(item);
      // console.log(i);
      this.jiage.push(item);
      this.jiage=[...new Set(this.jiage)]
      // console.log(item.name);
      this.$layer.msg("添加成功")
    },
    jianjian(i) {
      var k = i.num;
      i.num--
      if (k <=0) {
        i.num = 0;
      } 
    },
    xiang(v) {
      // 参数v代表当前点击图片的数据进行对应数据的渲染
      this.$router.push({path:"/xiangqing2",query: {id: v}});
      this.xian = v;
    },
  
    gun() {
      for(let m=0;m<this.changdu.length;m++){
        if(event.target.scrollTop+1>=this.changdu[m]){
            this.i=m
        }
      }
    },
  },
 
};
</script>

<style lang="less" scoped>
svg{
  width: 0.4rem;
  height: 0.4rem;
}
#shangping {
  display: flex;

  height: calc(100vh - 3.48rem);
  .left {
    width: 1.6rem;
    overflow-y: scroll;

    ul {
      width: 1.6rem;
      background: #f3f5f7;

      height: 100%;

      li {
        position: relative;
        width: 1.6rem;

        height: 0.99rem;
        
        &::after {
          position: absolute;
          content: "";
          width: 1.12rem;
          height: 0.01rem;
          bottom: 0;
          background: rgba(0, 0, 0, 0.4);
        }
      }
    }
  }
  .right {
    overflow-y: scroll;
    // width: 100%;
    width: calc(100vw - 1.6rem);

   

    .box {
      li {
        & > p {
          padding: 0 0.36rem;
          line-height: 0.5rem;
          height: 0.5rem;
          background: #f3f5f7;
        }
        ul {
          li {
            position: relative;
            padding: 0.36rem;
            &:not(:last-child)::after {
              content: "";
              position: absolute;
              bottom: 0;
              left: 0.36rem;
              width: calc(90vw - 1.6rem);

              border-bottom: 1px solid rgba(20, 15, 15, 0.7);
            }
            background: white;
            .img {
              width: 1.15rem;
            }
            .cont-r {
              flex: 1;
            }
            .tubiao {
              align-self: flex-end;
              svg {
                background: white;
                fill: #00a0dc;
              }
            }
          }
        }
      }
    }
  }
}

.right-enter-active {
  animation: fadeInUp 2s;
}
.v-enter-active {
  animation: fadeInRight 2s;
}
.del {
  text-decoration: line-through;
}

.xian {
  display: block;
  animation: dong 2s;
}

@keyframes dong {
  0% {
    transform: translateX(200px) rotate(350deg);
  }
  100% {
    transform: translateX(0px) rotate(0);
  }
}


</style>