<template>
  <div id="gouwuche">
    <!--  gouwuche -->
    <div class="gouwuche flex flex-ac white">
      <div
        class="ml30 tubiao"
        :style="shui.length > 0 ? 'background:#00a0dc;' : ''"
        @click="is = !is"
      >
      <!-- 购物车是否高亮取决于shui的长度 进行判断使用三元表达式判断购物车内的长度是否大于0 -->
        <svg
          :style="shui.length > 0 ? 'fill:white; background: #00a0dc;' : ''"
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          
          viewBox="0 0 768 768"
        >
          <g id="icomoon-ignore">
            <line
              stroke-width="1"
              x1="16"
              y1="0"
              x2="16"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="32"
              y1="0"
              x2="32"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="48"
              y1="0"
              x2="48"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="64"
              y1="0"
              x2="64"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="80"
              y1="0"
              x2="80"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="96"
              y1="0"
              x2="96"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="112"
              y1="0"
              x2="112"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="128"
              y1="0"
              x2="128"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="144"
              y1="0"
              x2="144"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="160"
              y1="0"
              x2="160"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="176"
              y1="0"
              x2="176"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="192"
              y1="0"
              x2="192"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="208"
              y1="0"
              x2="208"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="224"
              y1="0"
              x2="224"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="240"
              y1="0"
              x2="240"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="256"
              y1="0"
              x2="256"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="272"
              y1="0"
              x2="272"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="288"
              y1="0"
              x2="288"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="304"
              y1="0"
              x2="304"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="320"
              y1="0"
              x2="320"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="336"
              y1="0"
              x2="336"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="352"
              y1="0"
              x2="352"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="368"
              y1="0"
              x2="368"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="384"
              y1="0"
              x2="384"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="400"
              y1="0"
              x2="400"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="416"
              y1="0"
              x2="416"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="432"
              y1="0"
              x2="432"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="448"
              y1="0"
              x2="448"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="464"
              y1="0"
              x2="464"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="480"
              y1="0"
              x2="480"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="496"
              y1="0"
              x2="496"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="512"
              y1="0"
              x2="512"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="528"
              y1="0"
              x2="528"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="544"
              y1="0"
              x2="544"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="560"
              y1="0"
              x2="560"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="576"
              y1="0"
              x2="576"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="592"
              y1="0"
              x2="592"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="608"
              y1="0"
              x2="608"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="624"
              y1="0"
              x2="624"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="640"
              y1="0"
              x2="640"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="656"
              y1="0"
              x2="656"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="672"
              y1="0"
              x2="672"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="688"
              y1="0"
              x2="688"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="704"
              y1="0"
              x2="704"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="720"
              y1="0"
              x2="720"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="736"
              y1="0"
              x2="736"
              y2="768"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="752"
              y1="0"
              x2="752"
              y2="768"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="16"
              x2="768"
              y2="16"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="32"
              x2="768"
              y2="32"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="48"
              x2="768"
              y2="48"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="64"
              x2="768"
              y2="64"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="80"
              x2="768"
              y2="80"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="96"
              x2="768"
              y2="96"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="112"
              x2="768"
              y2="112"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="128"
              x2="768"
              y2="128"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="144"
              x2="768"
              y2="144"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="160"
              x2="768"
              y2="160"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="176"
              x2="768"
              y2="176"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="192"
              x2="768"
              y2="192"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="208"
              x2="768"
              y2="208"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="224"
              x2="768"
              y2="224"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="240"
              x2="768"
              y2="240"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="256"
              x2="768"
              y2="256"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="272"
              x2="768"
              y2="272"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="288"
              x2="768"
              y2="288"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="304"
              x2="768"
              y2="304"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="320"
              x2="768"
              y2="320"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="336"
              x2="768"
              y2="336"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="352"
              x2="768"
              y2="352"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="368"
              x2="768"
              y2="368"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="384"
              x2="768"
              y2="384"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="400"
              x2="768"
              y2="400"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="416"
              x2="768"
              y2="416"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="432"
              x2="768"
              y2="432"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="448"
              x2="768"
              y2="448"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="464"
              x2="768"
              y2="464"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="480"
              x2="768"
              y2="480"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="496"
              x2="768"
              y2="496"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="512"
              x2="768"
              y2="512"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="528"
              x2="768"
              y2="528"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="544"
              x2="768"
              y2="544"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="560"
              x2="768"
              y2="560"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="576"
              x2="768"
              y2="576"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="592"
              x2="768"
              y2="592"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="608"
              x2="768"
              y2="608"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="624"
              x2="768"
              y2="624"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="640"
              x2="768"
              y2="640"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="656"
              x2="768"
              y2="656"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="672"
              x2="768"
              y2="672"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="688"
              x2="768"
              y2="688"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="704"
              x2="768"
              y2="704"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="720"
              x2="768"
              y2="720"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="736"
              x2="768"
              y2="736"
              stroke="#449FDB"
              opacity="1"
            ></line>
            <line
              stroke-width="1"
              x1="0"
              y1="752"
              x2="768"
              y2="752"
              stroke="#449FDB"
              opacity="0.3"
            ></line>
          </g>
          <path
            d="M544.5 576q25.5 0 44.25 19.5t18.75 45-18.75 44.25-44.25 18.75-45-18.75-19.5-44.25 19.5-45 45-19.5zM31.5 64.5h105l30 63h474q13.5 0 22.5 9.75t9 23.25q0 7.5-4.5 15l-114 207q-18 33-55.5 33h-238.5l-28.5 52.5-1.5 4.5q0 7.5 7.5 7.5h370.5v64.5h-384q-25.5 0-44.25-19.5t-18.75-45q0-15 7.5-30l43.5-79.5-115.5-243h-64.5v-63zM223.5 576q25.5 0 45 19.5t19.5 45-19.5 44.25-45 18.75-44.25-18.75-18.75-44.25 18.75-45 44.25-19.5z"
          ></path>
        </svg>
      </div>
      <div class="font32 fb gray mlr10" :style="he > 0 ? 'color:white' : ''">
        ￥{{ he }}
      </div>
      <div class="font32 gray pei">另需配送费￥4</div>
      <!-- 使用v-if进行判断 判断是否大于0 -->
      <div class="font32 gray qi" v-if="cha - he > 0">￥{{ cha - he }}起送</div>
      <div
        class="font32 gray qi"
        v-else
        style="background: green; color: white"
        @click="jie"
      >
        结算
      </div>
    </div>

    <transition>
      <div class="zhezhao" v-show="is">
        <div class="bai">
          <div class="flex flex-jb plr30 flex-ac font30">
            <span>购物车</span>
            <span class="blue" @click="qing">清空</span>
          </div>

          <ul class="plr30">
            <li
              v-for="(item, index) in shui"
              :key="index"
              class="ptb25 flex flex-jb"
            >
              <div class="font32">{{ item.name }}</div>
              <div class="flex flex-ac">
                <span class="red font28 fb mr10">{{ item.price }}￥</span>

                <svg
                  @click="jian(item, index)"
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  width="40"
                  height="40"
                  viewBox="0 0 768 768"
                >
                  <g id="icomoon-ignore">
                    <line
                      stroke-width="1"
                      x1="16"
                      y1="0"
                      x2="16"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="32"
                      y1="0"
                      x2="32"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="48"
                      y1="0"
                      x2="48"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="64"
                      y1="0"
                      x2="64"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="80"
                      y1="0"
                      x2="80"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="96"
                      y1="0"
                      x2="96"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="112"
                      y1="0"
                      x2="112"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="128"
                      y1="0"
                      x2="128"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="144"
                      y1="0"
                      x2="144"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="160"
                      y1="0"
                      x2="160"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="176"
                      y1="0"
                      x2="176"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="192"
                      y1="0"
                      x2="192"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="208"
                      y1="0"
                      x2="208"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="224"
                      y1="0"
                      x2="224"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="240"
                      y1="0"
                      x2="240"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="256"
                      y1="0"
                      x2="256"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="272"
                      y1="0"
                      x2="272"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="288"
                      y1="0"
                      x2="288"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="304"
                      y1="0"
                      x2="304"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="320"
                      y1="0"
                      x2="320"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="336"
                      y1="0"
                      x2="336"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="352"
                      y1="0"
                      x2="352"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="368"
                      y1="0"
                      x2="368"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="384"
                      y1="0"
                      x2="384"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="400"
                      y1="0"
                      x2="400"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="416"
                      y1="0"
                      x2="416"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="432"
                      y1="0"
                      x2="432"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="448"
                      y1="0"
                      x2="448"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="464"
                      y1="0"
                      x2="464"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="480"
                      y1="0"
                      x2="480"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="496"
                      y1="0"
                      x2="496"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="512"
                      y1="0"
                      x2="512"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="528"
                      y1="0"
                      x2="528"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="544"
                      y1="0"
                      x2="544"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="560"
                      y1="0"
                      x2="560"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="576"
                      y1="0"
                      x2="576"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="592"
                      y1="0"
                      x2="592"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="608"
                      y1="0"
                      x2="608"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="624"
                      y1="0"
                      x2="624"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="640"
                      y1="0"
                      x2="640"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="656"
                      y1="0"
                      x2="656"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="672"
                      y1="0"
                      x2="672"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="688"
                      y1="0"
                      x2="688"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="704"
                      y1="0"
                      x2="704"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="720"
                      y1="0"
                      x2="720"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="736"
                      y1="0"
                      x2="736"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="752"
                      y1="0"
                      x2="752"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="16"
                      x2="768"
                      y2="16"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="32"
                      x2="768"
                      y2="32"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="48"
                      x2="768"
                      y2="48"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="64"
                      x2="768"
                      y2="64"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="80"
                      x2="768"
                      y2="80"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="96"
                      x2="768"
                      y2="96"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="112"
                      x2="768"
                      y2="112"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="128"
                      x2="768"
                      y2="128"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="144"
                      x2="768"
                      y2="144"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="160"
                      x2="768"
                      y2="160"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="176"
                      x2="768"
                      y2="176"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="192"
                      x2="768"
                      y2="192"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="208"
                      x2="768"
                      y2="208"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="224"
                      x2="768"
                      y2="224"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="240"
                      x2="768"
                      y2="240"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="256"
                      x2="768"
                      y2="256"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="272"
                      x2="768"
                      y2="272"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="288"
                      x2="768"
                      y2="288"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="304"
                      x2="768"
                      y2="304"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="320"
                      x2="768"
                      y2="320"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="336"
                      x2="768"
                      y2="336"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="352"
                      x2="768"
                      y2="352"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="368"
                      x2="768"
                      y2="368"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="384"
                      x2="768"
                      y2="384"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="400"
                      x2="768"
                      y2="400"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="416"
                      x2="768"
                      y2="416"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="432"
                      x2="768"
                      y2="432"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="448"
                      x2="768"
                      y2="448"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="464"
                      x2="768"
                      y2="464"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="480"
                      x2="768"
                      y2="480"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="496"
                      x2="768"
                      y2="496"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="512"
                      x2="768"
                      y2="512"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="528"
                      x2="768"
                      y2="528"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="544"
                      x2="768"
                      y2="544"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="560"
                      x2="768"
                      y2="560"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="576"
                      x2="768"
                      y2="576"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="592"
                      x2="768"
                      y2="592"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="608"
                      x2="768"
                      y2="608"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="624"
                      x2="768"
                      y2="624"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="640"
                      x2="768"
                      y2="640"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="656"
                      x2="768"
                      y2="656"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="672"
                      x2="768"
                      y2="672"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="688"
                      x2="768"
                      y2="688"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="704"
                      x2="768"
                      y2="704"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="720"
                      x2="768"
                      y2="720"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="736"
                      x2="768"
                      y2="736"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="752"
                      x2="768"
                      y2="752"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                  </g>
                  <path
                    d="M384 640.5q105 0 180.75-75.75t75.75-180.75-75.75-180.75-180.75-75.75-180.75 75.75-75.75 180.75 75.75 180.75 180.75 75.75zM384 64.5q132 0 225.75 93.75t93.75 225.75-93.75 225.75-225.75 93.75-225.75-93.75-93.75-225.75 93.75-225.75 225.75-93.75zM223.5 352.5h321v63h-321v-63z"
                  ></path>
                </svg>

                <i class="font30 mlr20">{{ item.num }}</i>

                <svg
                  @click="sh(item, index)"
                  :ref="index"
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  width="40"
                  height="40"
                  viewBox="0 0 768 768"
                >
                  <g id="icomoon-ignore">
                    <line
                      stroke-width="1"
                      x1="16"
                      y1="0"
                      x2="16"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="32"
                      y1="0"
                      x2="32"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="48"
                      y1="0"
                      x2="48"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="64"
                      y1="0"
                      x2="64"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="80"
                      y1="0"
                      x2="80"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="96"
                      y1="0"
                      x2="96"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="112"
                      y1="0"
                      x2="112"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="128"
                      y1="0"
                      x2="128"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="144"
                      y1="0"
                      x2="144"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="160"
                      y1="0"
                      x2="160"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="176"
                      y1="0"
                      x2="176"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="192"
                      y1="0"
                      x2="192"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="208"
                      y1="0"
                      x2="208"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="224"
                      y1="0"
                      x2="224"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="240"
                      y1="0"
                      x2="240"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="256"
                      y1="0"
                      x2="256"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="272"
                      y1="0"
                      x2="272"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="288"
                      y1="0"
                      x2="288"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="304"
                      y1="0"
                      x2="304"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="320"
                      y1="0"
                      x2="320"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="336"
                      y1="0"
                      x2="336"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="352"
                      y1="0"
                      x2="352"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="368"
                      y1="0"
                      x2="368"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="384"
                      y1="0"
                      x2="384"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="400"
                      y1="0"
                      x2="400"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="416"
                      y1="0"
                      x2="416"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="432"
                      y1="0"
                      x2="432"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="448"
                      y1="0"
                      x2="448"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="464"
                      y1="0"
                      x2="464"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="480"
                      y1="0"
                      x2="480"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="496"
                      y1="0"
                      x2="496"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="512"
                      y1="0"
                      x2="512"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="528"
                      y1="0"
                      x2="528"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="544"
                      y1="0"
                      x2="544"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="560"
                      y1="0"
                      x2="560"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="576"
                      y1="0"
                      x2="576"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="592"
                      y1="0"
                      x2="592"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="608"
                      y1="0"
                      x2="608"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="624"
                      y1="0"
                      x2="624"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="640"
                      y1="0"
                      x2="640"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="656"
                      y1="0"
                      x2="656"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="672"
                      y1="0"
                      x2="672"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="688"
                      y1="0"
                      x2="688"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="704"
                      y1="0"
                      x2="704"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="720"
                      y1="0"
                      x2="720"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="736"
                      y1="0"
                      x2="736"
                      y2="768"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="752"
                      y1="0"
                      x2="752"
                      y2="768"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="16"
                      x2="768"
                      y2="16"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="32"
                      x2="768"
                      y2="32"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="48"
                      x2="768"
                      y2="48"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="64"
                      x2="768"
                      y2="64"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="80"
                      x2="768"
                      y2="80"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="96"
                      x2="768"
                      y2="96"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="112"
                      x2="768"
                      y2="112"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="128"
                      x2="768"
                      y2="128"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="144"
                      x2="768"
                      y2="144"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="160"
                      x2="768"
                      y2="160"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="176"
                      x2="768"
                      y2="176"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="192"
                      x2="768"
                      y2="192"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="208"
                      x2="768"
                      y2="208"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="224"
                      x2="768"
                      y2="224"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="240"
                      x2="768"
                      y2="240"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="256"
                      x2="768"
                      y2="256"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="272"
                      x2="768"
                      y2="272"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="288"
                      x2="768"
                      y2="288"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="304"
                      x2="768"
                      y2="304"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="320"
                      x2="768"
                      y2="320"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="336"
                      x2="768"
                      y2="336"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="352"
                      x2="768"
                      y2="352"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="368"
                      x2="768"
                      y2="368"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="384"
                      x2="768"
                      y2="384"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="400"
                      x2="768"
                      y2="400"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="416"
                      x2="768"
                      y2="416"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="432"
                      x2="768"
                      y2="432"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="448"
                      x2="768"
                      y2="448"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="464"
                      x2="768"
                      y2="464"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="480"
                      x2="768"
                      y2="480"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="496"
                      x2="768"
                      y2="496"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="512"
                      x2="768"
                      y2="512"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="528"
                      x2="768"
                      y2="528"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="544"
                      x2="768"
                      y2="544"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="560"
                      x2="768"
                      y2="560"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="576"
                      x2="768"
                      y2="576"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="592"
                      x2="768"
                      y2="592"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="608"
                      x2="768"
                      y2="608"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="624"
                      x2="768"
                      y2="624"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="640"
                      x2="768"
                      y2="640"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="656"
                      x2="768"
                      y2="656"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="672"
                      x2="768"
                      y2="672"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="688"
                      x2="768"
                      y2="688"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="704"
                      x2="768"
                      y2="704"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="720"
                      x2="768"
                      y2="720"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="736"
                      x2="768"
                      y2="736"
                      stroke="#449FDB"
                      opacity="1"
                    ></line>
                    <line
                      stroke-width="1"
                      x1="0"
                      y1="752"
                      x2="768"
                      y2="752"
                      stroke="#449FDB"
                      opacity="0.3"
                    ></line>
                  </g>
                  <path
                    d="M544.5 415.5v-63h-129v-129h-63v129h-129v63h129v129h63v-129h129zM384 64.5q132 0 225.75 93.75t93.75 225.75-93.75 225.75-225.75 93.75-225.75-93.75-93.75-225.75 93.75-225.75 225.75-93.75z"
                  ></path>
                </svg>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
export default {
  // 购物车通过props接收传递过来的值
  props: ["jiage"],
  data() {
    return {
      cha: 20,
      shui: [],
      is: false,
      a:4
    };
  },
  // 通过计算属性
  computed: {
    he() {
      var k = 0;
      this.jiage.forEach((d) => {
        // console.log(d);
        // 购物车的总数等于单价乘以数量
        k += d.num * d.price;
      });

      return k;
    },
  },
  methods: {
    //加
    sh(i) {
      i.num++;
      this.shui = [...new Set(this.shui)];
      this.shui.push(i);
    },
    // 减
    jian(i, index) {
      var k = i.num;
      if (k <= 0) {
        i.num = 0;
        this.shui.splice(index, 1);
      } else {
        i.num--;
      }
    },
    // 清空
    qing() {
      var i = this.shui.length;
      for (var k = 0; k < i; k++) {
        this.jiage[k].num=0;
        // this.jiage[k].num=null;
      }
      this.shui = [];
      console.log(this.shui);
      
    },
    // 结算
    jie() {
      alert(this.he+this.a);
    },
    
  },
  // 使用watch监听将其发生改变的赋值到数组中，进行遍历插值
  watch: {
    jiage: {
      deep: true,
      handler(val) {
        var k = val.filter((d) => d.num != 0);
        this.shui =k;
        
      },
    },
  },

};
</script>

<style lang="less" scoped>
.v-enter-active {
  animation: fadeInUp 1s;
}

.gouwuche {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;

  height: 0.96rem;
  background: #141d27;

  z-index: 5;
  // padding-left: 100px;
}
.qi {
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2.1rem;
  background: #2b333b;
}
.pei {
  flex: 1;
}
.tubiao {
  position: relative;
  top: -0.2rem;
  border-radius: 50%;
  overflow: hidden;
  height: 1rem;
  width: 1rem;
  display: flex;
  // padding-left: 100px;
  align-items: center;
  justify-content: center;
  background: #80858a;
  border: 0.1rem solid #131d26;
  svg {
    fill: #2b343c;
    background: #80858a;
  }
}
.zhezhao {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  // width: 100px;
  overflow: hidden;
  height: 13.36rem;
  z-index: 4;
  background: rgba(0, 0, 0, 0.5);
  .bai {
    position: absolute;
    bottom: 0;
    width: 100%;
    padding-bottom: 0.9rem;
    overflow: scroll;
    height: 6.1rem;
    background: white;
    & > div {
      height: 0.8rem;
      background: #f3f5f7;
      span {
        display: inline-block;
        height: 100%;
        padding: 0 0.1rem;
        line-height: 0.8rem;
      }
    }
    & > ul {
      li {
        border-bottom: 0.01rem solid #80858a;
        & > div:last-child {
          svg {
            background: white;
            fill: #00a0dc;
          }
        }
      }
    }
  }
}
svg{
   width: 0.4rem;
  height: 0.4rem;
}
</style>